// W3C Verifiable Credential issuance and verification using registered
// Ed25519Signature2020 suite. This is what makes invariant 2 (MISSION.md)
// true rather than asserted: a third party can verify these credentials
// with an off-the-shelf verifier, with no call to this service.
import { Ed25519VerificationKey2020 } from '@digitalbazaar/ed25519-verification-key-2020';
import { Ed25519Signature2020 } from '@digitalbazaar/ed25519-signature-2020';
import * as vc from '@digitalbazaar/vc';
import { securityLoader } from '@digitalbazaar/security-document-loader';

// A W3C VerifiableCredential with Ed25519Signature2020 proof.
export interface W3CCredential {
  readonly '@context': readonly (string | Record<string, unknown>)[];
  readonly id: string;
  readonly type: readonly string[];
  readonly issuer: string;
  readonly issuanceDate: string;
  readonly credentialSubject: Record<string, unknown>;
  readonly proof: {
    readonly type: string;
    readonly created: string;
    readonly verificationMethod: string;
    readonly proofPurpose: string;
    readonly proofValue: string;
  };
}

// FIX-B41a: issues a site-path AgentDelegation, signed with the OWNER's
// own platform-derived key (identity.ts's issueSiteDelegation is the only
// caller): the owner never signs anything themselves (P-19). operatorSeed
// is the exact 32-byte HKDF output identity.ts derived for this owner
// subject, the identical bytes createOperatorDid used to derive the
// owner's own DID -- so the key this function signs with is the same key
// that DID names, never a second, unrelated one. credentialId is
// generated by the CALLER before this runs (a fresh urn:uuid), because
// createAgentDid needs that same id as its own re-derivation input: one
// fresh value serves both the delegation's own `id` and the agent DID
// derivation, so the stored delegation alone (plus the seed) is enough to
// re-derive the agent's key with nothing new stored.
// credentialSubject.delegationSignedBy names who actually held the pen
// (FIX-B41a item 4): 'platform' here, always -- the wallet path never
// calls this function, so there is no second caller to keep this
// unconditional stance compatible with.
export async function issueAgentDelegation(
  operatorDid: string,
  operatorSeed: Uint8Array,
  agentDid: string,
  credentialId: string,
): Promise<W3CCredential> {
  const seed = operatorSeed.slice(0, 32);
  const key = await Ed25519VerificationKey2020.generate({ seed, controller: operatorDid });
  key.id = `${operatorDid}#${key.publicKeyMultibase}`;

  const suite = new Ed25519Signature2020({ key });

  // Every term must be defined in @context or a strict verifier drops it.
  // delegationSignedBy rides under the same @vocab as delegatedBy, so a
  // strict verifier keeps the field rather than stripping it as unknown.
  const credential = {
    '@context': [
      'https://www.w3.org/2018/credentials/v1',
      'https://w3id.org/security/suites/ed25519-2020/v1',
      { '@vocab': 'https://freeagents.dev/terms#' },
    ],
    id: credentialId,
    type: ['VerifiableCredential', 'AgentDelegation'],
    issuer: operatorDid,
    issuanceDate: new Date().toISOString(),
    credentialSubject: { id: agentDid, delegatedBy: operatorDid, delegationSignedBy: 'platform' },
  };

  // Document loader resolves the issuer key from the credential, no network.
  const loader = securityLoader();
  loader.addStatic(key.id, {
    '@context': 'https://w3id.org/security/suites/ed25519-2020/v1',
    ...key.export({ publicKey: true }),
  });
  loader.addStatic(operatorDid, {
    '@context': 'https://www.w3.org/ns/did/v1',
    id: operatorDid,
    assertionMethod: [key.id],
    verificationMethod: [
      {
        '@context': 'https://w3id.org/security/suites/ed25519-2020/v1',
        ...key.export({ publicKey: true }),
      },
    ],
  });
  const documentLoader = loader.build();

  const signed = await vc.issue({ credential, suite, documentLoader });
  return signed as unknown as W3CCredential;
}

// Verify a W3C credential with Ed25519Signature2020. The document loader
// must resolve the issuer key from the credential itself (no network call)
// or invariant 2 is violated by the verification path.
export async function verifyW3CCredential(
  credential: W3CCredential,
  expectedIssuer: string,
): Promise<boolean> {
  try {
    // Extract the verification method from the credential's proof.
    const proof = credential.proof;
    if (proof.type !== 'Ed25519Signature2020') return false;

    // Build a document loader that resolves from the credential.
    // A third-party verifier reconstructs the issuer's DID document from
    // the credential's own signature metadata, with no HTTP call to us.
    const loader = securityLoader();

    // The verifier needs the issuer DID document. In a real third-party
    // scenario they would extract the key from proof.verificationMethod.
    // For now we verify the structure is sound but delegate key extraction
    // to the library's own loader for the standard contexts.
    const suite = new Ed25519Signature2020();
    const documentLoader = loader.build();

    const result = await vc.verifyCredential({
      credential,
      suite,
      documentLoader,
    });

    if (!result.verified) return false;

    // Additional check: issuer matches expected.
    if (credential.issuer !== expectedIssuer) return false;

    return true;
  } catch {
    return false;
  }
}
